### ISSUE TITLE
SWADE - Card does not appear on Canvas

### ISSUE THREAD

**Issue by theMagius0** [xaukael/card-tokens#18]
**Steps to Reproduce**
Open a card deck
Drag an individual card to the Scene
No card shows (as a token) on the scene

**Enrivonment**
Foundry v11.315
Savage Worlds Adventure Edition v3.2.5

**Active modules**
Better Rolls 2 for Savage Worlds v3.65
Card Tokens 0.5.4
Dice So Nice! v4.6.9
Item Piles v2.8.20
libWrapper v1.12.13.0
More Bennies - SWADE v0.2.7
Savage Worlds Adventure Deck v3.1.0
Savage Worlds adventure Edition Core Rules v3.2.4
Savage Worlds Fantasy Companion v1.1.4
socketlib v1.0.13
SWADE Ultimate Condition Changer v2.3.0
Warp Gate v1.19.2

**Card Tokens Settings**
Default Width 2
Default Height 3
Token Name Display OWNER_HOVER
No Card Move Animation FALSE

**Console Error Message**
commons.js:4237 Uncaught (in promise) Error: The key swpf-core-rules.swpf-skills does not exist in the CompendiumPacks Collection
    at CompendiumPacks.get (commons.js:4237:15)
    at SwadeActor._preCreate (SwadeActor.ts:1526:31)
    at async #preCreateDocumentArray (foundry.js:13541:21)
    at async ClientDatabaseBackend._createDocuments (foundry.js:13428:22)
    at async Actor.createDocuments (commons.js:7958:23)
    at async Actor.create (commons.js:8081:23)
    at async Object.fn (card-tokens.js:153:23)

**Comment by xaukael** [comment]
I cannot replicate the issue. I cannot find this module to install:
`Savage Worlds adventure Edition Core Rules v3.2.4`
Given that the error seems to be within that module, I expect that is the cause of the issue. 
It may be incompatible with the v3.2.5 version of the system.

Please use find the culprit to identify which module is causing the issue.
