### ISSUE TITLE
Compatibility with foundry12

### ISSUE THREAD

**Issue by meix13** [xaukael/card-tokens#20]
Are you planning to update it to support version 12? Thank you very much for your module :)
----- with foundry12:

card-tokens.js:156 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Actor')
    at Object.fn (card-tokens.js:156:44)
    at #call (foundry.js:608:20)
    at Hooks.callAll (foundry.js:565:17)
    at foundry-esm.js:56368:17
    at foundry-esm.js:56373:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry-esm.js:56373:33)
    at async Card.createDocuments (foundry-esm.js:11407:23)
    at async Promise.all (index 0)
    at async Cards.pass (foundry.js:16678:5)
    at async CardHandsList._onDrawCard (CardHandsList.mjs:283:26)

**Comment by xaukael** [comment]
This module depends on warpgate for the creation of the tokens. I have no plans to rewrite the module for v12 as of now.
